import type { NextPage } from "next";
import Head from "next/head";
import tw, { css } from "twin.macro";

const Home: NextPage = () => {
	const text = css`
		${tw`font-bold text-5xl text-red-500`}
		background-color: #333;
	`;
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<p css={text}>aaaaaa</p>
		</div>
	);
};

export default Home;
